name: 'Application API deployment (tasks)'

on:
  push:
    branches: [ main ]
    paths:
      - 'tasks/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario'
        required: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: ./tasks
        run: npm install
      - name: Run tests
        working-directory: ./tasks
        run: npm test

  deploy_to_render:
    needs:
      - build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API to Render
        if: github.ref == 'refs/heads/main'
        env:
          TASKS_DEPLOY_HOOK: ${{ secrets.TASKS_DEPLOY_HOOK }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST $TASKS_DEPLOY_HOOK)
          if [ $response -eq 200 ]
          then
              echo "Deployed successfully"
          else
              echo "Deploy failed"
              exit 1
          fi